# Generated by Django 5.0.2 on 2024-03-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_oc', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_oc', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_oc', models.DateField()),
                ('hora_oc', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
                ('id_estado_oc_fk', models.ForeignKey(blank=True, db_column='id_estado_oc_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='estado_oc.estadooc')),
                ('id_proveedor_fk', models.ForeignKey(blank=True, db_column='id_proveedor_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
            options={
                'db_table': 'orden_compra',
            },
        ),
    ]
