# Generated by Django 5.0.2 on 2024-03-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estado_pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_pedido', models.CharField(max_length=255)),
                ('fecha_pedido', models.DateField()),
                ('calificacion_pedido', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_estado_pedido_fk', models.ForeignKey(blank=True, db_column='id_estado_pedido_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='estado_pedido.estadopedido')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
    ]
