# Generated by Django 5.0.2 on 2024-03-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_fin_pedido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
