# Generated by Django 5.0.2 on 2024-03-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('subtotal_detalle_venta', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_producto_fk', models.ForeignKey(blank=True, db_column='id_producto_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'db_table': 'detalle_venta',
            },
        ),
    ]
