# Generated by Django 5.0.2 on 2024-03-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalle_venta', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='id_venta_fk',
            field=models.ForeignKey(blank=True, db_column='id_venta_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.venta'),
        ),
    ]
