# Generated by Django 5.0.2 on 2024-03-12 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
                ('hora_venta', models.TimeField()),
                ('total_venta', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_pedido_fk', models.ForeignKey(blank=True, db_column='id_pedido_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('no_documento_usuario_fk', models.ForeignKey(blank=True, db_column='no_documento_usuario_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venta',
            },
        ),
    ]
