# Generated by Django 5.0.2 on 2024-03-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
        ('orden_compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOC',
            fields=[
                ('id_detalle_oc', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_insumo', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_insumo_fk', models.ForeignKey(blank=True, db_column='id_insumo_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo')),
                ('id_oc_fk', models.ForeignKey(blank=True, db_column='id_oc_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='orden_compra.ordencompra')),
            ],
            options={
                'db_table': 'detalle_oc',
            },
        ),
    ]
