# Generated by Django 5.0.2 on 2024-03-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estado_insumo', '0001_initial'),
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='id_estado_insumo',
        ),
        migrations.AddField(
            model_name='insumo',
            name='id_estado_insumo_fk',
            field=models.ForeignKey(blank=True, db_column='id_estado_insumo_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='estado_insumo.estadoinsumo'),
        ),
    ]
