# Generated by Django 5.0.2 on 2024-03-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('comentario_calificacion', models.TextField()),
                ('estrellas_calificacion', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_proveedor_fk', models.ForeignKey(blank=True, db_column='id_proveedor_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
    ]
